import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./backoffice/components/Sidebar";
import NavBar from "./backoffice/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className="flex flex-col h-screen">
        <NavBar />
        <div className="flex flex-grow">
          <Sidebar />
          <main className="flex-grow p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
